items = [
  {
    '_id': '1',
    'name': 'Airpods Wireless Bluetooth Headphones',
    'category': ['Electronics', 'Apple'],
    'image': '/images/airpods.jpg',
    'currently': None,
    'buy_price': 149.99,
    'first_bid': 89.99,
    'number_of_bids': None,
    'bids': None,
    'location': 'Athens',
    'country': 'Greece',
    'started': None,
    'ends': None,
    'seller': 'Bob',
    'description':
    'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
  },
  {
    '_id': '2',
    'name': 'iPhone 11 Pro 256GB Memory',
    'category': ['Electronics', 'Apple'],
    'image': '/images/phone.jpg',
    'currently': None,
    'buy_price': 699.99,
    'first_bid': 599.99,
    'number_of_bids': None,
    'bids': None,
    'location': 'Athens',
    'country': 'Greece',
    'started': None,
    'ends': None,
    'seller': 'Mike',
    'description':
    'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
  },
]
