export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST'
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL'

export const ITEM_PLACE_BID_REQUEST = 'ITEM_PLACE_BID_REQUEST'
export const ITEM_PLACE_BID_SUCCESS = 'ITEM_PLACE_BID_SUCCESS'
export const ITEM_PLACE_BID_FAIL = 'ITEM_PLACE_BID_FAIL'
export const ITEM_PLACE_BID_RESET = 'ITEM_PLACE_BID_RESET'