# Generated by Django 3.2.15 on 2022-09-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_bid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currently', models.DecimalField(blank=True, decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=7), max_digits=7, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('number_of_bids', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7, null=True)),
                ('bids', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ends', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
