# Generated by Django 4.1.1 on 2022-09-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', upload_to='')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_bid', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('currently', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('number_of_bids', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7)),
                ('bids', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Not started', 'Not started'), ('Active', 'Active'), ('Concluded', 'Concluded')], max_length=200, null=True)),
                ('saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='none', max_length=15)),
                ('country', models.CharField(default='none', max_length=100)),
                ('city', models.CharField(default='none', max_length=100)),
                ('address', models.CharField(default='none', max_length=100)),
                ('TIN', models.CharField(default='none', max_length=20)),
                ('seller_rating', models.IntegerField(blank=True, null=True)),
                ('bidder_rating', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('visits', models.ManyToManyField(to='base.item')),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
