# Generated by Django 4.1.1 on 2022-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_delete_entries_remove_item_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visits',
            field=models.ManyToManyField(blank=True, to='base.item'),
        ),
    ]
