# Generated by Django 3.2.15 on 2022-09-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
    ]
