# Generated by Django 4.1.1 on 2022-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
    ]
